### PR TITLE
corrected webserver.java

### PR DESCRIPTION
**Pull request by onelots**
corrected a lil mistake : "retuning anything" instead of "returning anything" (thanks AfonsoHacker)

### CODE REVIEW

**Comment by jensjeflensje** [comment]
Hi, thanks for your PR! Right now, the English wording is still not quite correct if I'm not mistaken. Could you make it a correct sentence? I'd be happy to accept your PR then :)

**Comment by Norbiros** [comment]
`Skript.warning("You are not returning anything from a web server request!")`
Grammatically good sentence :)

Please change this and close request.

**Comment by jensjeflensje** [comment]
Could you commit & push this? It would be cool to add one tot the contributors list :)

**Comment by jensjeflensje** [comment]
Closing as this has been fixed in another PR

**Pull request closed without merging**
